/**
 * Runtime configuration.
 * Override DATA_FILE_PATH or PORT via environment variables when deploying.
 *
 * Default data file path resolves from:
 *   backend/src/config.ts  →  ../../projects/arg-portal/src/assets/data/
 *
 * In production, set DATA_FILE_PATH to the real data store location.
 */
import path from 'path';

export const config = {
  port: Number(process.env.PORT ?? 3000),

  // Full-detail JSON generated by scripts/excel_to_neural_json.py
  // This file lives in frontend assets for local dev (mock), but should move
  // to a backend-only location (or real DB) before production.
  dataFilePath: process.env.DATA_FILE_PATH ??
    path.resolve(__dirname, '..', '..', 'projects', 'arg-portal', 'src', 'assets', 'data', 'neural_schema.json'),

  // Allowed CORS origins — frontend dev server ports
  corsOrigins: (process.env.CORS_ORIGINS ?? 'http://localhost:4200,http://localhost:4201').split(','),
} as const;
